--Création des différentes tables dans la base de données Projet 
Use Projet

CREATE TABLE CLIENT(
    ID_CLIENT INT IDENTITY(1,1) PRIMARY KEY,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    DATE_NAISSANCE DATE,
    DATE_PREMIER_ACHAT DATE
);

CREATE TABLE ADRESSE(
    ID_ADRESSE INT IDENTITY(1,1) PRIMARY KEY,
    NUMERO INT,
    NOM_RUE VARCHAR(50),
    NOM_VILLE VARCHAR(50),
    CODE_POSTAL VARCHAR(50),
    TYPE_ADRESSE INT
);

CREATE TABLE PERSONNEL(
    ID_PERSONNEL INT IDENTITY(1,1) PRIMARY KEY,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    DATE_EMBAUCHE DATE,
    SUPERIEUR_HIERARCHIQUE VARCHAR(50),
    ID_POSTE INT
);

CREATE TABLE COMMANDE(
    ID_COMMANDE INT IDENTITY(1,1) PRIMARY KEY,
    DATE_EMISSION DATE,
    DATE_LIVRAISON DATE,
    DATE_REGLEMENT DATE,
    ID_CLIENT INT,
    ID_PRODUIT INT,
    MOYEN_PAIEMENT VARCHAR(50),
    TOTAL_ARTICLES_HT REAL,
    TOTAL_TVA REAL,
    TOTAL_TTC REAL,
    FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);

CREATE TABLE CATALOGUE_PRODUIT(
    ID_PRODUIT INT IDENTITY(1,1) PRIMARY KEY,
    REF_PRODUIT VARCHAR(50),
    PRIX_HT_FIXE REAL,
    DESIGNATION VARCHAR(50),
    TAUX_TVA REAL,
	ID_ARTICLE INT,
    HISTORIQUE_FACTURATION DATE
);

CREATE TABLE FACTURE(
    ID_FACTURE INT IDENTITY(1,1) PRIMARY KEY,
    MOYEN_PAIEMENT VARCHAR(50),
    DATE_PAIEMENT DATE,
    PRIX_TOTAL_HT REAL,
    MONTANT_TOTAL_TVA REAL,
    PRIX_TOTAL_TTC REAL,
    MONTANT_REMISE REAL,
    TOTAL_APRES_REMISE REAL,
    ID_CLIENT INT,
    ID_COMMANDE INT,
    FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY(ID_COMMANDE) REFERENCES COMMANDE(ID_COMMANDE)
);

CREATE TABLE ENTREPOT(
    ID_ENTREPOT INT IDENTITY(1,1) PRIMARY KEY,
	NOM_ENTREPOT VARCHAR(50)
);

CREATE TABLE ARTICLE(
    ID_ARTICLE INT IDENTITY(1,1) PRIMARY KEY,
    NOM_ARTICLE VARCHAR(50),
    REMISE_COMMERCIALE REAL,
    PRIX_UNITAIRE REAL,
    TVA REAL,
    ID_PRODUIT INT,
    FOREIGN KEY(ID_PRODUIT) REFERENCES CATALOGUE_PRODUIT(ID_PRODUIT)
);

CREATE TABLE POSSEDE1(
    ID_CLIENT INT,
    ID_ADRESSE INT,
    PRIMARY KEY(ID_CLIENT, ID_ADRESSE),
    FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY(ID_ADRESSE) REFERENCES ADRESSE(ID_ADRESSE)
);

CREATE TABLE POSSEDE2(
    ID_ADRESSE INT,
    ID_PERSONNEL INT,
    PRIMARY KEY(ID_ADRESSE, ID_PERSONNEL),
    FOREIGN KEY(ID_ADRESSE) REFERENCES ADRESSE(ID_ADRESSE),
    FOREIGN KEY(ID_PERSONNEL) REFERENCES PERSONNEL(ID_PERSONNEL)
);

CREATE TABLE CONTIENT(
    ID_COMMANDE INT,
    ID_ARTICLE INT,
    QUANTITE_ARTICLE INT,
    PRIMARY KEY(ID_COMMANDE, ID_ARTICLE),
    FOREIGN KEY(ID_COMMANDE) REFERENCES COMMANDE(ID_COMMANDE),
    FOREIGN KEY(ID_ARTICLE) REFERENCES ARTICLE(ID_ARTICLE)
);

CREATE TABLE PROVIENT2(
    ID_PRODUIT INT,
    ID_ENTREPOT INT,
    QUANTITE_PRODUIT_STOCK VARCHAR(50),
    SEUIL_REAPPROVISIONNEMENT INT,
    PRIMARY KEY(ID_PRODUIT, ID_ENTREPOT),
    FOREIGN KEY(ID_PRODUIT) REFERENCES CATALOGUE_PRODUIT(ID_PRODUIT),
    FOREIGN KEY(ID_ENTREPOT) REFERENCES ENTREPOT(ID_ENTREPOT)
);

CREATE TABLE PANIER(
    ID_PANIER INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENT INT,
    ID_ARTICLE INT,
    QUANTITE INT,
    DATE_AJOUT DATE,
    PRIX_HT_FIXE REAL,
	ID_PRODUIT INT,
    TAUX_TVA REAL,
    FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY(ID_ARTICLE) REFERENCES ARTICLE(ID_ARTICLE)
);
CREATE TABLE DETAIL_COMMANDE(
    ID_DETAIL_COMMANDE INT IDENTITY(1,1) PRIMARY KEY,
    ID_COMMANDE INT,
    ID_ARTICLE INT,
    QUANTITE INT,
    PRIX_UNITAIRE REAL,
    FOREIGN KEY(ID_COMMANDE) REFERENCES COMMANDE(ID_COMMANDE),
    FOREIGN KEY(ID_ARTICLE) REFERENCES ARTICLE(ID_ARTICLE)
);


-- Insertion des différents entrepôts dans la table ENTREPOT 
USE Projet

INSERT INTO ENTREPOT(NOM_ENTREPOT)
VALUES ('ROUEN')

INSERT INTO ENTREPOT(NOM_ENTREPOT)
VALUES ('PARIS')

INSERT INTO ENTREPOT(NOM_ENTREPOT)
VALUES ('MARSEILLE')

INSERT INTO ENTREPOT(NOM_ENTREPOT)
VALUES ('LILLE')